<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="TopMovies.DAL\TopMovies.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TopMovies.DAL\**\*.cs" />
    <Content Remove="TopMovies.DAL\**\*" />
    <None Remove="TopMovies.DAL\**\*" />
  </ItemGroup>

</Project>
