// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopMovies.Data;

#nullable disable

namespace TopMovies.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TopMovies.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Банкір Енді Дюфрейн, засуджений за вбивство, яке не скоював, знаходить надію та дружбу за стінами в'язниці Шоушенк.",
                            Director = "Френк Дарабонт",
                            Genre = "Драма",
                            PosterPath = "/images/posters/shawshank.svg",
                            ReleaseYear = 1994,
                            Title = "Втеча з Шоушенка"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Історія родини Корлеоне та боротьби за владу в світі організованої злочинності Нью-Йорка.",
                            Director = "Френсіс Форд Коппола",
                            Genre = "Кримінал, драма",
                            PosterPath = "/images/posters/godfather.svg",
                            ReleaseYear = 1972,
                            Title = "Хрещений батько"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Бетмен протистоїть Джокеру, який занурює Готем у хаос та випробовує моральні межі героя.",
                            Director = "Крістофер Нолан",
                            Genre = "Бойовик, кримінал",
                            PosterPath = "/images/posters/darkknight.svg",
                            ReleaseYear = 2008,
                            Title = "Темний лицар"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Переплетені історії найманих вбивць, боксера та бандита у Лос-Анджелесі.",
                            Director = "Квентін Тарантіно",
                            Genre = "Кримінал, драма",
                            PosterPath = "/images/posters/pulpfiction.svg",
                            ReleaseYear = 1994,
                            Title = "Кримінальне чтиво"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Викрадач думок отримує завдання здійснити зворотну операцію — вкласти ідею у чужу підсвідомість.",
                            Director = "Крістофер Нолан",
                            Genre = "Фантастика, трилер",
                            PosterPath = "/images/posters/inception.svg",
                            ReleaseYear = 2010,
                            Title = "Початок"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Історія простодушного чоловіка з Алабами, який став свідком та учасником ключових подій американської історії.",
                            Director = "Роберт Земекіс",
                            Genre = "Драма, мелодрама",
                            PosterPath = "/images/posters/forrestgump.svg",
                            ReleaseYear = 1994,
                            Title = "Форрест Гамп"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Група дослідників вирушає крізь червоточину в пошуках нового дому для людства.",
                            Director = "Крістофер Нолан",
                            Genre = "Фантастика, драма",
                            PosterPath = "/images/posters/interstellar.svg",
                            ReleaseYear = 2014,
                            Title = "Інтерстеллар"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Бідна родина поступово проникає у життя заможного сімейства, що призводить до непередбачуваних наслідків.",
                            Director = "Пон Джун Хо",
                            Genre = "Трилер, драма",
                            PosterPath = "/images/posters/parasite.svg",
                            ReleaseYear = 2019,
                            Title = "Паразити"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
